name: Verify OpenAI secret

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm secret presence
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "❌ Secret is missing"
            exit 1
          else
            echo "✅ Secret is available (length: ${#OPENAI_API_KEY})"
          fi
